/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vehicle;

import pack1.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulex Sandoval
 * 
 **/
public class NewVehicle extends javax.swing.JFrame {

    /**
     * Creates new form NewLog
     */
    private final VisitorPanel visitorPanel;

    public NewVehicle(int visitorID, VisitorPanel visitorPanel) {
        this.visitorPanel = visitorPanel;
        initComponents();
        VisitorIDTF.setText(Integer.toString(visitorID));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SubmitLog = new javax.swing.JButton();
        CancelLog = new javax.swing.JButton();
        PlateField = new javax.swing.JTextField();
        TypeCB = new javax.swing.JComboBox<>();
        ModelField = new javax.swing.JTextField();
        VisitorIDTF = new javax.swing.JTextField();
        PlateLabel = new javax.swing.JLabel();
        VisitorIDLabel = new javax.swing.JLabel();
        ModelLabel = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TitleLabel.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        TitleLabel.setText("New Vehicle");

        SubmitLog.setBackground(new java.awt.Color(46, 110, 76));
        SubmitLog.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        SubmitLog.setForeground(new java.awt.Color(255, 255, 255));
        SubmitLog.setText("Submit");
        SubmitLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLogActionPerformed(evt);
            }
        });

        CancelLog.setBackground(new java.awt.Color(46, 110, 76));
        CancelLog.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        CancelLog.setForeground(new java.awt.Color(255, 255, 255));
        CancelLog.setText("Cancel");
        CancelLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLogActionPerformed(evt);
            }
        });

        PlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateFieldActionPerformed(evt);
            }
        });

        TypeCB.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        TypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motorcycle", "SUV", "Pickup", "Sedan" }));
        TypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeCBActionPerformed(evt);
            }
        });

        VisitorIDTF.setText("VisitorID:");
        VisitorIDTF.setEnabled(false);
        VisitorIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorIDTFActionPerformed(evt);
            }
        });

        PlateLabel.setBackground(new java.awt.Color(0, 0, 0));
        PlateLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        PlateLabel.setText("Plate Number");

        VisitorIDLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        VisitorIDLabel.setText("VisitorID");

        ModelLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        ModelLabel.setText("Vehicle Model");

        TypeLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        TypeLabel.setText("Vehicle Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModelField)
                    .addComponent(VisitorIDTF)
                    .addComponent(PlateField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TypeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PlateLabel)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ModelLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TypeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VisitorIDLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CancelLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisitorIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisitorIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitLog)
                    .addComponent(CancelLog))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void SubmitLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLogActionPerformed
        // TODO add your handling code here:
        //Transfers VehicleRecord to Database
        String SqlQuery = "select *  from vehicle where PlateNumber = ?";
        try {//Opens Database for First Statement
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
            PreparedStatement pst = conn.prepareStatement(SqlQuery);
            pst.setString(1, PlateField.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) { //Same VehiclePlate is Detected
                JOptionPane.showMessageDialog(null, "Vehicle Plate already Exist", "Existing Vehicle", JOptionPane.PLAIN_MESSAGE);
            } else { //New VehiclePlate
                conn.close();
                System.out.println("NEXT");
                System.out.println(TypeCB.getSelectedItem());
                String SqlInsert = "insert into vehicle values(?,?,?,?)";
                try { //Checks Second Statement
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
                    pst = conn.prepareStatement(SqlInsert);
                    pst.setString(1, PlateField.getText());
                    pst.setObject(2, TypeCB.getSelectedItem());
                    pst.setString(3, ModelField.getText());
                    pst.setString(4, VisitorIDTF.getText());
                    pst.executeUpdate();
                    conn.close();
                    visitorPanel.showVehicleTable();
                    dispose();
                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showOptionDialog(null, "Error Detected on Insert", "Catch Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
                }
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showOptionDialog(null, "Error Detected on Select", "Catch Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
        }
    }//GEN-LAST:event_SubmitLogActionPerformed

    private void CancelLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLogActionPerformed
        // TODO add your handling code here:
        dispose(); //Closes PopUp

    }//GEN-LAST:event_CancelLogActionPerformed

    private void PlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateFieldActionPerformed

    private void TypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeCBActionPerformed

    private void VisitorIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitorIDTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelLog;
    private javax.swing.ButtonGroup InputGroup;
    private javax.swing.JTextField ModelField;
    private javax.swing.JLabel ModelLabel;
    private javax.swing.JTextField PlateField;
    private javax.swing.JLabel PlateLabel;
    private javax.swing.JButton SubmitLog;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JComboBox<String> TypeCB;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel VisitorIDLabel;
    private javax.swing.JTextField VisitorIDTF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
