/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vehicle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Win10
 */
public class PanelActionDeleteButton extends javax.swing.JPanel {

    /**
     * Creates new form PanelDelVehicle
     */
    public PanelActionDeleteButton() {
        initComponents();
    }
    
    public void initEvent(TableActionEventDelete event, int row){
        delVehicleButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delVehicleButton = new Super_Admin.ActionButtonEdit();

        delVehicleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/del.png"))); // NOI18N
        delVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delVehicleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delVehicleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delVehicleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Super_Admin.ActionButtonEdit delVehicleButton;
    // End of variables declaration//GEN-END:variables
}
