/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack1;

import java.sql.*;
import javax.swing.JOptionPane;
import Objects.*;
import java.awt.event.*;

/**
 *
 * @author Paulex Sandoval
 * 
 **/
public class NewLog extends javax.swing.JFrame {

    /**
     * Creates new form NewLog
     **/
    private final int visitID, visitorID, staffID;
    Log newLog;
    private VisitorPanel visitorPanel;
    private Resident resident = new Resident();
    private Facility facility = new Facility();

    public NewLog(int visitID, int visitorID, int staffID, VisitorPanel visitorPanel) {
        this.visitorPanel = visitorPanel;
        initComponents();
        VisitIDTF.setText(Integer.toString(visitID));
        VisitorIDTF.setText(Integer.toString(visitorID));
        SecIDTF.setText(Integer.toString(staffID));
        this.visitID = visitID;
        this.visitorID = visitorID;
        this.staffID = staffID;
        newLog = new Log();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SubmitLog = new javax.swing.JButton();
        CancelLog = new javax.swing.JButton();
        VisitIDTF = new javax.swing.JTextField();
        VisitorIDTF = new javax.swing.JTextField();
        SecIDTF = new javax.swing.JTextField();
        VisitIDLabel = new javax.swing.JLabel();
        VisitorIDLabel = new javax.swing.JLabel();
        StaffIDLabel = new javax.swing.JLabel();
        LocationPanel = new javax.swing.JPanel();
        BlockLabel = new javax.swing.JLabel();
        BlockCB = new javax.swing.JComboBox<>();
        LotLabel = new javax.swing.JLabel();
        LotCB = new javax.swing.JComboBox<>();
        PhaseLabel = new javax.swing.JLabel();
        PhaseCB = new javax.swing.JComboBox<>();
        LocationTitleLabel = new javax.swing.JLabel();
        ResidentPanel = new javax.swing.JPanel();
        FNameLabel = new javax.swing.JLabel();
        MNameLabel = new javax.swing.JLabel();
        LNameLabel = new javax.swing.JLabel();
        SNameLabel = new javax.swing.JLabel();
        ResidentTitleLabel = new javax.swing.JLabel();
        FNameField = new javax.swing.JTextField();
        MNameField = new javax.swing.JTextField();
        LNameField = new javax.swing.JTextField();
        SNameField = new javax.swing.JTextField();
        FacilityPanel = new javax.swing.JPanel();
        FacilityNameLabel = new javax.swing.JLabel();
        FacilityNameCB = new javax.swing.JComboBox<>();
        FacilityLabel = new javax.swing.JLabel();
        StaffIDLabel1 = new javax.swing.JLabel();
        LocationRB = new javax.swing.JRadioButton();
        ResidentRB = new javax.swing.JRadioButton();
        FacilityRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TitleLabel.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        TitleLabel.setText("New Log");

        SubmitLog.setBackground(new java.awt.Color(46, 110, 76));
        SubmitLog.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        SubmitLog.setForeground(new java.awt.Color(255, 255, 255));
        SubmitLog.setText("Submit");
        SubmitLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLogActionPerformed(evt);
            }
        });

        CancelLog.setBackground(new java.awt.Color(46, 110, 76));
        CancelLog.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        CancelLog.setForeground(new java.awt.Color(255, 255, 255));
        CancelLog.setText("Cancel");
        CancelLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLogActionPerformed(evt);
            }
        });

        VisitIDTF.setText("VisitID:");
        VisitIDTF.setEnabled(false);
        VisitIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitIDTFActionPerformed(evt);
            }
        });

        VisitorIDTF.setText("VisitorID:");
        VisitorIDTF.setEnabled(false);

        SecIDTF.setText("StaffID:");
        SecIDTF.setEnabled(false);

        VisitIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        VisitIDLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        VisitIDLabel.setText("VisitID");

        VisitorIDLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        VisitorIDLabel.setText("VisitorID");

        StaffIDLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        StaffIDLabel.setText("StaffID");

        BlockLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        BlockLabel.setText("Block");

        BlockCB.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        BlockCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        BlockCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockCBActionPerformed(evt);
            }
        });

        LotLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        LotLabel.setText("Lot");

        LotCB.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LotCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        PhaseLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        PhaseLabel.setText("Phase");

        PhaseCB.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        PhaseCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        LocationTitleLabel.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        LocationTitleLabel.setText("Choose Location Address");

        javax.swing.GroupLayout LocationPanelLayout = new javax.swing.GroupLayout(LocationPanel);
        LocationPanel.setLayout(LocationPanelLayout);
        LocationPanelLayout.setHorizontalGroup(
            LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlockLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LocationPanelLayout.createSequentialGroup()
                        .addComponent(LocationTitleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BlockCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LotCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhaseCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LocationPanelLayout.setVerticalGroup(
            LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LocationPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(LocationTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BlockCB)
                    .addComponent(BlockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LotCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhaseLabel)
                    .addComponent(PhaseCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ResidentPanel.setVisible(false);

        FNameLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        FNameLabel.setText("First Name");

        MNameLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        MNameLabel.setText("Middle Name");

        LNameLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        LNameLabel.setText("Last Name");

        SNameLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        SNameLabel.setText("Suffix");

        ResidentTitleLabel.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        ResidentTitleLabel.setText("Type Resident Name");

        MNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNameFieldActionPerformed(evt);
            }
        });

        LNameField.setToolTipText("");
        LNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameFieldActionPerformed(evt);
            }
        });

        SNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResidentPanelLayout = new javax.swing.GroupLayout(ResidentPanel);
        ResidentPanel.setLayout(ResidentPanelLayout);
        ResidentPanelLayout.setHorizontalGroup(
            ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResidentPanelLayout.createSequentialGroup()
                .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResidentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(FNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ResidentPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ResidentTitleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResidentPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FNameField, LNameField, MNameField, SNameField});

        ResidentPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FNameLabel, LNameLabel, MNameLabel, SNameLabel});

        ResidentPanelLayout.setVerticalGroup(
            ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResidentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(MNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(LNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResidentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(SNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ResidentPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FNameField, LNameField, MNameField, SNameField});

        FacilityPanel.setVisible(false);

        FacilityNameLabel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        FacilityNameLabel.setText("Facility Name");

        FacilityNameCB.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        FacilityNameCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Club House", "Basketball Court", "Football Court", "Chapel" }));
        FacilityNameCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacilityNameCBActionPerformed(evt);
            }
        });

        FacilityLabel.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        FacilityLabel.setText("Choose Facility");

        javax.swing.GroupLayout FacilityPanelLayout = new javax.swing.GroupLayout(FacilityPanel);
        FacilityPanel.setLayout(FacilityPanelLayout);
        FacilityPanelLayout.setHorizontalGroup(
            FacilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FacilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FacilityNameLabel)
                .addGap(24, 24, 24)
                .addComponent(FacilityNameCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FacilityPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(FacilityLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FacilityPanelLayout.setVerticalGroup(
            FacilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FacilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FacilityLabel)
                .addGap(18, 18, 18)
                .addGroup(FacilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FacilityNameCB)
                    .addComponent(FacilityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StaffIDLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        StaffIDLabel1.setText("Input Types");

        InputGroup.add(LocationRB);
        LocationRB.setSelected(true);
        LocationRB.setText("Location");
        LocationRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LocationRBItemStateChanged(evt);
            }
        });
        LocationRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationRBActionPerformed(evt);
            }
        });

        InputGroup.add(ResidentRB);
        ResidentRB.setText("Resident Name");
        ResidentRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ResidentRBItemStateChanged(evt);
            }
        });
        ResidentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentRBActionPerformed(evt);
            }
        });

        InputGroup.add(FacilityRB);
        FacilityRB.setText("Facility Name");
        FacilityRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FacilityRBItemStateChanged(evt);
            }
        });
        FacilityRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacilityRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResidentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LocationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VisitIDLabel)
                        .addGap(261, 261, 261))
                    .addComponent(VisitIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisitorIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FacilityPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CancelLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StaffIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VisitorIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StaffIDLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LocationRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResidentRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FacilityRB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VisitIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisitIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisitorIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisitorIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(StaffIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StaffIDLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocationRB)
                    .addComponent(ResidentRB)
                    .addComponent(FacilityRB))
                .addGap(30, 30, 30)
                .addComponent(LocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResidentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FacilityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitLog)
                    .addComponent(CancelLog))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int checkValidLocation() {
        //if return 0 = Not a Valid Location, if return 1 = Valid Location, if return -1 = Error
        String SqlSelect = "Select * from Location_tb where BlockNum = ? and LotNum = ? and PhaseNum = ?";
        int block = BlockCB.getSelectedIndex() + 1;
        int lot = LotCB.getSelectedIndex() + 1;
        int phase = PhaseCB.getSelectedIndex() + 1;
        try { //Opens Database
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
            PreparedStatement pst = conn.prepareStatement(SqlSelect);
            pst.setInt(1, block);
            pst.setInt(2, lot);
            pst.setInt(3, phase);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                conn.close();
                return 1;
            } else {
                conn.close();
                return 0;
            }
        } catch (ClassNotFoundException | SQLException e) {
            //Logger.getLogger(NewLog.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }


    private void SubmitLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLogActionPerformed
        // TODO add your handling code here:
        //Submits NewLog Record to Database
        if (LocationRB.isSelected()) {//RadioButton Location is Selected
            if (checkValidLocation() == 1) { //Valid Location Detected
                String SqlQuery = "insert into visitor_log(VisitID,VisitorID,BlockNum,LotNum,PhaseNum,Security_InCharge) values(?,?,?,?,?,?)";
                try { //Opens Database
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
                    PreparedStatement pst = conn.prepareStatement(SqlQuery);
                    pst.setInt(1, visitID);
                    pst.setInt(2, visitorID);
                    pst.setInt(3, BlockCB.getSelectedIndex() + 1);
                    pst.setInt(4, LotCB.getSelectedIndex() + 1);
                    pst.setInt(5, PhaseCB.getSelectedIndex() + 1);
                    pst.setInt(6, staffID);
                    pst.executeUpdate();
                    conn.close();
                    System.out.println(newLog.setInfo(visitorID));
                    newLog.updateDateTime();
                    visitorPanel.refreshLogs();
                    dispose(); //Closes PopUp
                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showOptionDialog(null, "Catch Error", "Catch Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Input a Valid Location", "Invalid Location", JOptionPane.ERROR_MESSAGE);
            }
        } else if (ResidentRB.isSelected()) { //RadioButton Resident is Selected
            int resNew=3;
            if (LNameField.getText().isEmpty() || FNameField.getText().isEmpty()) { //Checks Valid Resident Name in Database
            JOptionPane.showMessageDialog(null, "Please Enter Last Name and First Name", "Invalid Input", JOptionPane.PLAIN_MESSAGE);
        } else if (MNameField.getText().isEmpty() && SNameField.getText().isEmpty()) {
            resNew = resident.setInfo(LNameField.getText(), FNameField.getText());
        } else if (SNameField.getText().isEmpty()) {
            resNew = resident.setInfo(LNameField.getText(), FNameField.getText(), MNameField.getText());
        } else if (MNameField.getText().isEmpty()) {
            resNew = resident.setInfo(LNameField.getText(), FNameField.getText(), SNameField.getText());
        } else {
            resNew = resident.setInfo(LNameField.getText(), FNameField.getText(), MNameField.getText(), SNameField.getText());
        }
            if(resNew==0){ //No resident Info Detected
                JOptionPane.showMessageDialog(null, "Resident Name given is not valid. Please enter a valid Resident ", "Invalid Resident", JOptionPane.PLAIN_MESSAGE);
            }else if(resNew==1){ //Resident Info Detected
                String SqlQuery = "insert into visitor_log(VisitID,VisitorID,BlockNum,LotNum,PhaseNum,Security_InCharge) values(?,?,?,?,?,?)";
                try { //Opens Database
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
                    PreparedStatement pst = conn.prepareStatement(SqlQuery);
                    pst.setInt(1, visitID);
                    pst.setInt(2, visitorID);
                    pst.setInt(3, resident.getBlock());
                    pst.setInt(4, resident.getLot());
                    pst.setInt(5, resident.getPhase());
                    pst.setInt(6, staffID);
                    pst.executeUpdate();
                    conn.close();
                    System.out.println(newLog.setInfo(visitorID));
                    newLog.updateDateTime();
                    visitorPanel.refreshLogs();
                    dispose();
                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showOptionDialog(null, "Catch Error", "Catch Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
                }
            }
        } else if (FacilityRB.isSelected()) {  //RadioButton Facility is Selected
            int block = 0, lot = 0, phase = 0;
            switch (FacilityNameCB.getSelectedIndex()) { // Sets Location Address depending on the Facility selected (0 = ClubHouse, 1 = Basketball Court, 2 = Football Court, 3 = Chapel)
                case 0 -> {
                    block = 2;
                    lot = 1;
                    phase = 1;
                }
                case 1 -> {
                    block = 2;
                    lot = 2;
                    phase = 1;
                }
                case 2 -> {
                    block = 2;
                    lot = 1;
                    phase = 2;
                }
                case 3 -> {
                    block = 2;
                    lot = 2;
                    phase = 2;
                }
            }
            int stat = facility.checkStatus(block, lot, phase); //Checks if the Chosen Facility is Closed or Not
            switch (stat) { // -1 Facility is Closed, 0 Unknown Facility Address, 2 Catch Error, 1 Facility is Open
                case -1 -> JOptionPane.showMessageDialog(null, "Current Facility is Closed", "Closed Facility", JOptionPane.PLAIN_MESSAGE);
                case 0 -> JOptionPane.showMessageDialog(null, "No Record", "No Record", JOptionPane.PLAIN_MESSAGE);
                case 2 -> JOptionPane.showMessageDialog(null, "Caught the Error", "Error Occured", JOptionPane.PLAIN_MESSAGE);
                case 1 -> {
                    String SqlQuery = "insert into visitor_log(VisitID,VisitorID,BlockNum,LotNum,PhaseNum,Security_InCharge) values(?,?,?,?,?,?)";
                    try { //Opens Database
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
                        PreparedStatement pst = conn.prepareStatement(SqlQuery);
                        pst.setInt(1, visitID);
                        pst.setInt(2, visitorID);
                        pst.setInt(3, block);
                        pst.setInt(4,lot);
                        pst.setInt(5, phase);
                        pst.setInt(6, staffID);
                        pst.executeUpdate();
                        conn.close();
                        System.out.println(newLog.setInfo(visitorID));
                        newLog.updateDateTime();
                        visitorPanel.refreshLogs();
                        dispose(); //Closes PopUp
                    } catch (ClassNotFoundException | SQLException e) {
                        JOptionPane.showOptionDialog(null, "Catch Error", "Catch Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
                    }
                }
            }
        }


    }//GEN-LAST:event_SubmitLogActionPerformed

    private void CancelLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLogActionPerformed
        // TODO add your handling code here:
        dispose(); //Closes PopUp
    }//GEN-LAST:event_CancelLogActionPerformed

    private void VisitIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitIDTFActionPerformed

    private void BlockCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlockCBActionPerformed

    private void MNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNameFieldActionPerformed

    private void LNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameFieldActionPerformed

    private void SNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNameFieldActionPerformed

    private void FacilityNameCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacilityNameCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacilityNameCBActionPerformed

    private void LocationRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationRBActionPerformed

    private void ResidentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResidentRBActionPerformed

    private void FacilityRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacilityRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacilityRBActionPerformed

    private void LocationRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LocationRBItemStateChanged
        // TODO add your handling code here:
        //Changes to Location Panel
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            LocationPanel.setVisible(true);
            ResidentPanel.setVisible(false);
            FacilityPanel.setVisible(false);
        }
    }//GEN-LAST:event_LocationRBItemStateChanged

    private void ResidentRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ResidentRBItemStateChanged
        // TODO add your handling code here:
        //Changes to Resident Panel
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            LocationPanel.setVisible(false);
            ResidentPanel.setVisible(true);
            FacilityPanel.setVisible(false);
        }
    }//GEN-LAST:event_ResidentRBItemStateChanged

    private void FacilityRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FacilityRBItemStateChanged
        // TODO add your handling code here:
        //Changes to Facility Panel
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            LocationPanel.setVisible(false);
            ResidentPanel.setVisible(false);
            FacilityPanel.setVisible(true);
        }
    }//GEN-LAST:event_FacilityRBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BlockCB;
    private javax.swing.JLabel BlockLabel;
    private javax.swing.JButton CancelLog;
    private javax.swing.JTextField FNameField;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JLabel FacilityLabel;
    private javax.swing.JComboBox<String> FacilityNameCB;
    private javax.swing.JLabel FacilityNameLabel;
    private javax.swing.JPanel FacilityPanel;
    private javax.swing.JRadioButton FacilityRB;
    private javax.swing.ButtonGroup InputGroup;
    private javax.swing.JTextField LNameField;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JPanel LocationPanel;
    private javax.swing.JRadioButton LocationRB;
    private javax.swing.JLabel LocationTitleLabel;
    private javax.swing.JComboBox<String> LotCB;
    private javax.swing.JLabel LotLabel;
    private javax.swing.JTextField MNameField;
    private javax.swing.JLabel MNameLabel;
    private javax.swing.JComboBox<String> PhaseCB;
    private javax.swing.JLabel PhaseLabel;
    private javax.swing.JPanel ResidentPanel;
    private javax.swing.JRadioButton ResidentRB;
    private javax.swing.JLabel ResidentTitleLabel;
    private javax.swing.JTextField SNameField;
    private javax.swing.JLabel SNameLabel;
    private javax.swing.JTextField SecIDTF;
    private javax.swing.JLabel StaffIDLabel;
    private javax.swing.JLabel StaffIDLabel1;
    private javax.swing.JButton SubmitLog;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel VisitIDLabel;
    private javax.swing.JTextField VisitIDTF;
    private javax.swing.JLabel VisitorIDLabel;
    private javax.swing.JTextField VisitorIDTF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
