
package Super_Admin;

public class addPeopleSA extends javax.swing.JPanel {

    /**
     * Creates new form addPeopleSA
     */
    public addPeopleSA() {
        initComponents();
   
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        people = new javax.swing.JLabel();
        addBL = new javax.swing.JLabel();
        addResident = new javax.swing.JButton();
        addSec = new javax.swing.JButton();
        resOrSec = new javax.swing.JTabbedPane();
        blank = new javax.swing.JPanel();
        res = new javax.swing.JPanel();
        addResident1 = new Super_Admin.addResident();
        sec = new javax.swing.JPanel();
        addSec1 = new Super_Admin.addSec();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 749));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        people.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        people.setForeground(new java.awt.Color(30, 30, 30));
        people.setText("People");
        add(people, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 45, -1, -1));

        addBL.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        addBL.setForeground(new java.awt.Color(133, 133, 133));
        addBL.setText("Add new resident or security personnel in the subdivision");
        add(addBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 113, -1, -1));

        addResident.setBackground(new java.awt.Color(46, 110, 76));
        addResident.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        addResident.setForeground(new java.awt.Color(255, 255, 255));
        addResident.setText("+ Resident");
        addResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResidentActionPerformed(evt);
            }
        });
        add(addResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 56, -1, 50));

        addSec.setBackground(new java.awt.Color(46, 110, 76));
        addSec.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        addSec.setForeground(new java.awt.Color(255, 255, 255));
        addSec.setText("+ Security");
        addSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSecActionPerformed(evt);
            }
        });
        add(addSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 56, -1, 50));

        resOrSec.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        blank.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout blankLayout = new javax.swing.GroupLayout(blank);
        blank.setLayout(blankLayout);
        blankLayout.setHorizontalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
        );
        blankLayout.setVerticalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        resOrSec.addTab("tab2", blank);

        res.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resLayout = new javax.swing.GroupLayout(res);
        res.setLayout(resLayout);
        resLayout.setHorizontalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(addResident1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        resLayout.setVerticalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resLayout.createSequentialGroup()
                .addComponent(addResident1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        resOrSec.addTab("tab3", res);

        sec.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout secLayout = new javax.swing.GroupLayout(sec);
        sec.setLayout(secLayout);
        secLayout.setHorizontalGroup(
            secLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addSec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        secLayout.setVerticalGroup(
            secLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secLayout.createSequentialGroup()
                .addComponent(addSec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        resOrSec.addTab("tab3", sec);

        add(resOrSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 160, 1330, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void addSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSecActionPerformed
        resOrSec.setSelectedIndex(2);
    }//GEN-LAST:event_addSecActionPerformed

    private void addResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResidentActionPerformed
        resOrSec.setSelectedIndex(1);
    }//GEN-LAST:event_addResidentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBL;
    private javax.swing.JButton addResident;
    private Super_Admin.addResident addResident1;
    private javax.swing.JButton addSec;
    private Super_Admin.addSec addSec1;
    private javax.swing.JPanel blank;
    private javax.swing.JLabel people;
    private javax.swing.JPanel res;
    private javax.swing.JTabbedPane resOrSec;
    private javax.swing.JPanel sec;
    // End of variables declaration//GEN-END:variables
}
