package Super_Admin;

import Objects.*;
import java.awt.Color;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class addResident extends javax.swing.JPanel {

    String lname, fname, mname, suf, sex, bdate, email, phone, block, lot, phase, sexC;
    boolean lnameChecker, fnameChecker, mnameChecker, sufChecker, bdateChecker, emailChecker, phoneChecker, blockChecker, lotChecker, phaseChecker, successChecker; //checker kung tama ang user input

    /**
     * Creates new form addResident
     */
    public addResident() {
        initComponents();
        confirmationPanel2.setVisible(false);
    }

    public int getNextID() {
        String SqlQuery = "select MAX(ResidentID) from Resident";
        int out = 0;
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
            PreparedStatement pst = conn.prepareStatement(SqlQuery);
            ResultSet rs = pst.executeQuery();
            System.out.println("c");
            if (rs.next()) {
                System.out.println("a");
                out = rs.getInt(1);
                System.out.println(out);
                out++;
            }
        } catch (ClassNotFoundException | SQLException e) {
            return -1;
        }
        return out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPeoplePanel = new javax.swing.JPanel();
        FullNameLabel = new javax.swing.JLabel();
        LNameLabel1 = new javax.swing.JLabel();
        FNameLabel21 = new javax.swing.JLabel();
        MNameLabel1 = new javax.swing.JLabel();
        SuffixLabel1 = new javax.swing.JLabel();
        SexLabel1 = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        blockNum = new javax.swing.JLabel();
        lotNum = new javax.swing.JLabel();
        phaseNum = new javax.swing.JLabel();
        BDateLabel = new javax.swing.JLabel();
        LNameField2 = new javax.swing.JTextField();
        FNameField2 = new javax.swing.JTextField();
        MNameField2 = new javax.swing.JTextField();
        SuffixField2 = new javax.swing.JTextField();
        blockNumField = new javax.swing.JTextField();
        lotNumField = new javax.swing.JTextField();
        phaseNumField = new javax.swing.JTextField();
        residentConfirmPanel = new javax.swing.JPanel();
        SexCombo2 = new javax.swing.JComboBox<>();
        BdateField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        confirmationPanel2 = new javax.swing.JPanel();
        residentLabel2 = new javax.swing.JLabel();
        fnameLabel2 = new javax.swing.JLabel();
        sexLabel2 = new javax.swing.JLabel();
        bdateLabel2 = new javax.swing.JLabel();
        pnumberLabel2 = new javax.swing.JLabel();
        EmailLabel2 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        confirm2Button = new javax.swing.JButton();
        resNameLabel = new javax.swing.JLabel();
        resBdateLabel = new javax.swing.JLabel();
        resSexLabel1 = new javax.swing.JLabel();
        resEmailLabel = new javax.swing.JLabel();
        resAddressLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        resPhoneNumberLabel = new javax.swing.JLabel();
        residentIDLabel = new javax.swing.JLabel();
        resIDLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        addPeoplePanel.setVisible(true);
        addPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));
        addPeoplePanel.setPreferredSize(new java.awt.Dimension(753, 700));

        FullNameLabel.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        FullNameLabel.setText("Full Name");

        LNameLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        LNameLabel1.setText("Last Name*");

        FNameLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        FNameLabel21.setText("First Name*");

        MNameLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        MNameLabel1.setText("Middle Name");

        SuffixLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SuffixLabel1.setText("Suffix");

        SexLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SexLabel1.setText("Sex*");

        AddressLabel.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        AddressLabel.setText("Address");

        blockNum.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        blockNum.setText("Block*");

        lotNum.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lotNum.setText("Lot Number*");

        phaseNum.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        phaseNum.setText("Phase*");

        BDateLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BDateLabel.setText("Birthdate (yyyy-mm-dd)*");

        LNameField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        LNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameField2ActionPerformed(evt);
            }
        });

        FNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameField2ActionPerformed(evt);
            }
        });

        MNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNameField2ActionPerformed(evt);
            }
        });

        SuffixField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuffixField2ActionPerformed(evt);
            }
        });

        blockNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockNumFieldActionPerformed(evt);
            }
        });

        lotNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotNumFieldActionPerformed(evt);
            }
        });

        phaseNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseNumFieldActionPerformed(evt);
            }
        });

        residentConfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        residentConfirmPanel.setMinimumSize(new java.awt.Dimension(350, 50));

        SexCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        SexCombo2.setSelectedIndex(-1);
        SexCombo2.setPreferredSize(new java.awt.Dimension(330, 30));
        SexCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexCombo2ActionPerformed(evt);
            }
        });

        BdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdateFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout residentConfirmPanelLayout = new javax.swing.GroupLayout(residentConfirmPanel);
        residentConfirmPanel.setLayout(residentConfirmPanelLayout);
        residentConfirmPanelLayout.setHorizontalGroup(
            residentConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentConfirmPanelLayout.createSequentialGroup()
                .addComponent(SexCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        residentConfirmPanelLayout.setVerticalGroup(
            residentConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(residentConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        phoneNumberLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        phoneNumberLabel.setText("Phone Number*");

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        emailLabel.setText("Email*");

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(46, 110, 76));
        submitButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPeoplePanelLayout = new javax.swing.GroupLayout(addPeoplePanel);
        addPeoplePanel.setLayout(addPeoplePanelLayout);
        addPeoplePanelLayout.setHorizontalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SexLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNameLabel1)
                            .addComponent(LNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SuffixLabel1)
                                    .addComponent(BDateLabel))
                                .addGap(209, 209, 209))
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(SuffixField2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addComponent(FNameLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addComponent(FNameField2)
                                .addGap(38, 38, 38)))
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(MNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MNameLabel1))
                        .addGap(60, 60, 60))
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressLabel)
                            .addComponent(phaseNum)
                            .addComponent(FullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(residentConfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                    .addComponent(phaseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(295, 295, 295)
                                    .addComponent(submitButton))
                                .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                    .addComponent(blockNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(384, 384, 384)))
                            .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPeoplePanelLayout.createSequentialGroup()
                                    .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(phoneNumberLabel)))
                                .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                    .addComponent(blockNum)
                                    .addGap(318, 318, 318)
                                    .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lotNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                                            .addComponent(lotNum)
                                            .addGap(236, 236, 236))))))
                        .addContainerGap())))
        );
        addPeoplePanelLayout.setVerticalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(FullNameLabel)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNameLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuffixLabel1)
                    .addComponent(LNameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuffixField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDateLabel)
                    .addComponent(SexLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(residentConfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockNum)
                    .addComponent(lotNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phaseNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phaseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        residentLabel2.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        residentLabel2.setText("RESIDENT INFORMATION");

        fnameLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        fnameLabel2.setText("NAME:");

        sexLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        sexLabel2.setText("SEX:");

        bdateLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        bdateLabel2.setText("BIRTHDATE:");

        pnumberLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        pnumberLabel2.setText("PHONE NUMBER:");

        EmailLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        EmailLabel2.setText("EMAIL:");

        addressLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        addressLabel2.setText("ADDRESS:");

        confirm2Button.setBackground(new java.awt.Color(46, 110, 76));
        confirm2Button.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        confirm2Button.setForeground(new java.awt.Color(255, 255, 255));
        confirm2Button.setText("Confirm");
        confirm2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm2ButtonconfirmLabelActionPerformed(evt);
            }
        });

        resNameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        resBdateLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        resSexLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        resEmailLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        resAddressLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        cancelButton.setBackground(new java.awt.Color(46, 110, 76));
        cancelButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonconfirmLabelActionPerformed(evt);
            }
        });

        resPhoneNumberLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N

        residentIDLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        residentIDLabel.setForeground(new java.awt.Color(102, 102, 102));
        residentIDLabel.setText("RESIDENT ID: ");

        resIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        resIDLabel.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout confirmationPanel2Layout = new javax.swing.GroupLayout(confirmationPanel2);
        confirmationPanel2.setLayout(confirmationPanel2Layout);
        confirmationPanel2Layout.setHorizontalGroup(
            confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                        .addComponent(fnameLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resNameLabel))
                                    .addComponent(pnumberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(resPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(addressLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resAddressLabel))
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(bdateLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resBdateLabel))
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(sexLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resSexLabel1))
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(EmailLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, confirmationPanel2Layout.createSequentialGroup()
                                    .addComponent(residentIDLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(resIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(residentLabel2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(confirm2Button)
                        .addGap(38, 38, 38)
                        .addComponent(cancelButton)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        confirmationPanel2Layout.setVerticalGroup(
            confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(residentLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(residentIDLabel)
                    .addComponent(resIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel2)
                    .addComponent(resNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel2)
                    .addComponent(resSexLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdateLabel2)
                    .addComponent(resBdateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnumberLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resAddressLabel)
                    .addComponent(addressLabel2))
                .addGap(32, 32, 32)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPeoplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(confirmationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPeoplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameField2ActionPerformed

    private void FNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameField2ActionPerformed

    private void MNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNameField2ActionPerformed

    private void SuffixField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuffixField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuffixField2ActionPerformed

    private void blockNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockNumFieldActionPerformed

    private void lotNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotNumFieldActionPerformed

    private void phaseNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phaseNumFieldActionPerformed

    private void SexCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexCombo2ActionPerformed

    private void BdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BdateFieldActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Resident res = new Resident();

        //kukunin laman ng jfield
        lname = LNameField2.getText();
        fname = FNameField2.getText();
        mname = MNameField2.getText();
        suf = SuffixField2.getText();
        if (SexCombo2.getSelectedItem() != null) {
            sex = SexCombo2.getSelectedItem().toString();
        }
        bdate = BdateField.getText();
        email = emailField.getText();
        phone = phoneNumberField.getText();
        block = blockNumField.getText();
        lot = lotNumField.getText();
        phase = phaseNumField.getText();

        //gawing black ang text para pag nagreset
        LNameLabel1.setForeground(Color.black);
        FNameLabel21.setForeground(Color.black);
        MNameLabel1.setForeground(Color.black);
        SuffixLabel1.setForeground(Color.black);
        SexLabel1.setForeground(Color.black);
        BDateLabel.setForeground(Color.black);
        emailLabel.setForeground(Color.black);
        phoneNumberLabel.setForeground(Color.black);
        blockNum.setForeground(Color.black);
        lotNum.setForeground(Color.black);
        phaseNum.setForeground(Color.black);

        //check if may laman
        if (!"".equals(lname) && !"".equals(fname) && !"".equals(sex) && !"".equals(bdate) && !"".equals(email)
                && !"".equals(phone) && !"".equals(block) && !"".equals(lot)
                && !"".equals(phase) && SexCombo2.getSelectedItem() != null) {

            ///check kung tama ang laman
            if (res.isAlpha(lname)) {
                lnameChecker = true;
            } else {
                LNameLabel1.setForeground(Color.red);
            }

            if (res.isAlpha(fname)) {
                fnameChecker = true;
            } else {
                FNameLabel21.setForeground(Color.red);
            }

            if (!MNameField2.getText().isEmpty()) {
                if (res.isAlpha(mname)) {
                    mnameChecker = true;
                } else {
                    MNameLabel1.setForeground(Color.red);
                }
            }

            if (!SuffixField2.getText().isEmpty()) {
                if (res.isAlpha(suf)) {
                    sufChecker = true;
                } else {
                    SuffixLabel1.setForeground(Color.red);
                }
            }

            if (res.validateJavaDate(bdate)) {
                bdateChecker = true;
            } else {
                BDateLabel.setForeground(Color.red);
            }

            if (res.isValid(email)) {
                emailChecker = true;
            } else {
                emailLabel.setForeground(Color.red);
            }

            if (!res.isAlpha(phone) && phone.length() == 11) {
                phoneChecker = true;
            } else {
                phoneNumberLabel.setForeground(Color.red);
            }

            if (!res.isAlpha(block) && block.length() <= 2) {
                blockChecker = true;
            } else {
                blockNum.setForeground(Color.red);
            }

            if (!res.isAlpha(lot) && lot.length() <= 2) {
                lotChecker = true;
            } else {
                lotNum.setForeground(Color.red);
            }

            if (!res.isAlpha(phase) && phase.length() == 1) {
                phaseChecker = true;
            } else {
                phaseNum.setForeground(Color.red);
            }

            //id
            int id = getNextID();

            //set na ng mga info sa confirmation panel
            if (lnameChecker == true && fnameChecker == true && mnameChecker == true && sufChecker == true && bdateChecker == true
                    && emailChecker == true && phoneChecker == true && blockChecker == true && lotChecker == true && phaseChecker == true) {
                confirmationPanel2.setVisible(true);
                resIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + mname + " " + lname + " " + suf);
                resSexLabel1.setText(sex);
                resBdateLabel.setText(bdate);
                resPhoneNumberLabel.setText(phone);
                resEmailLabel.setText(email);
                resAddressLabel.setText("Block " + block + " Lot " + lot + " Phase " + phase + " ");
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == false && sufChecker == true && bdateChecker == true
                    && emailChecker == true && phoneChecker == true && blockChecker == true && lotChecker == true && phaseChecker == true) {
                confirmationPanel2.setVisible(true);
                resIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + lname + " " + suf);
                resSexLabel1.setText(sex);
                resBdateLabel.setText(bdate);
                resPhoneNumberLabel.setText(phone);
                resEmailLabel.setText(email);
                resAddressLabel.setText("Block " + block + " Lot " + lot + " Phase " + phase + " ");
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == true && sufChecker == false && bdateChecker == true
                    && emailChecker == true && phoneChecker == true && blockChecker == true && lotChecker == true && phaseChecker == true) {
                confirmationPanel2.setVisible(true);
                resIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + mname + " " + lname);
                resSexLabel1.setText(sex);
                resBdateLabel.setText(bdate);
                resPhoneNumberLabel.setText(phone);
                resEmailLabel.setText(email);
                resAddressLabel.setText("Block " + block + " Lot " + lot + " Phase " + phase + " ");
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == false && sufChecker == false && bdateChecker == true
                    && emailChecker == true && phoneChecker == true && blockChecker == true && lotChecker == true && phaseChecker == true) {
                confirmationPanel2.setVisible(true);
                resIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + lname);
                resSexLabel1.setText(sex);
                resBdateLabel.setText(bdate);
                resPhoneNumberLabel.setText(phone);
                resEmailLabel.setText(email);
                resAddressLabel.setText("Block " + block + " Lot " + lot + " Phase " + phase + " ");
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Input", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kindly Fill Out Required Details", "Message", JOptionPane.INFORMATION_MESSAGE);
        }

        //reset to false
        lnameChecker = false;
        fnameChecker = false;
        mnameChecker = false;
        sufChecker = false;
        bdateChecker = false;
        emailChecker = false;
        phoneChecker = false;
        blockChecker = false;
        lotChecker = false;
        phaseChecker = false;
    }//GEN-LAST:event_submitButtonActionPerformed

    private void confirm2ButtonconfirmLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm2ButtonconfirmLabelActionPerformed
        Resident res = new Resident();
        Security sec = new Security();

        int checkEmail = 0;
        int checkPhone = 0;
        int checkLoc = 0;
        int checkPhoneSec = 0;

        checkEmail = res.checkEmail(email);
        checkPhone = res.checkPhone(phone);
        checkPhoneSec = sec.checkPhone(phone);
        //If walang record
        if (checkEmail == 0 && checkPhone == 0 && checkPhoneSec == 0) {

            //check kung may existing block,lot,phase
            checkLoc = res.checkLoc(block, lot, phase);
            System.out.println(checkLoc);

            //if existing
            if (checkLoc == 1) {
                int id = getNextID();
                String sql = "insert into resident values(?,?,?,?,?,?,?,?,?,?,?,?)";

                try {
                    if ("Male".equals(sex)) {
                        sexC = "M";
                    } else {
                        sexC = "F";
                    }

                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");

                    System.out.println("Connect to database successful!!");

                    successChecker = true;

                    PreparedStatement pst = conn.prepareStatement(sql);

                    pst.setString(1, String.valueOf(id));
                    pst.setString(2, lname);
                    pst.setString(3, fname);
                    if (MNameField2.getText().isEmpty()) {
                        pst.setString(4, null);
                    } else {
                        pst.setString(4, mname);
                    }

                    if (SuffixField2.getText().isEmpty()) {
                        pst.setString(5, null);
                    } else {
                        pst.setString(5, suf);
                    }
                    pst.setString(6, sexC);
                    pst.setString(7, bdate);
                    pst.setString(8, email);
                    pst.setString(9, phone);
                    pst.setString(10, block);
                    pst.setString(11, lot);
                    pst.setString(12, phase);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Inserted Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                    //rs.close();
                    conn.close();

                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Not a residence", "Message", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            } else {//kapag di pa existing
                JOptionPane.showMessageDialog(null, "Location does not exist", "Message", JOptionPane.INFORMATION_MESSAGE);
                blockNum.setForeground(Color.red);
                lotNum.setForeground(Color.red);
                phaseNum.setForeground(Color.red);
            }
        } else {//kapag may record na nito
            JOptionPane.showMessageDialog(null, "This record already exist", "Message", JOptionPane.INFORMATION_MESSAGE);
            if (checkEmail == 1) {
                emailLabel.setForeground(Color.red);
            }
            if (checkPhone == 1 || checkPhoneSec == 1) {
                phoneNumberLabel.setForeground(Color.red);
            }

        }
        if (successChecker) {
            FNameField2.setText("");
            LNameField2.setText("");
            MNameField2.setText("");
            SuffixField2.setText("");
            SexCombo2.setSelectedIndex(-1);
            BdateField.setText("");
            emailField.setText("");
            phoneNumberField.setText("");
            blockNumField.setText("");
            lotNumField.setText("");
            phaseNumField.setText("");
            confirmationPanel2.setVisible(false);
            //reset
            successChecker = false;
        }
    }//GEN-LAST:event_confirm2ButtonconfirmLabelActionPerformed

    private void cancelButtonconfirmLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonconfirmLabelActionPerformed
        FNameField2.setText("");
        LNameField2.setText("");
        MNameField2.setText("");
        SuffixField2.setText("");
        SexCombo2.setSelectedIndex(-1);
        BdateField.setText("");
        emailField.setText("");
        phoneNumberField.setText("");
        blockNumField.setText("");
        lotNumField.setText("");
        phaseNumField.setText("");
        confirmationPanel2.setVisible(false);
        resNameLabel.setText("");
        resSexLabel1.setText("");
        resBdateLabel.setText("");
        resPhoneNumberLabel.setText("");
        resEmailLabel.setText("");
        resAddressLabel.setText("");

        //gawing black ang text para pag nagcancel
        LNameLabel1.setForeground(Color.black);
        FNameLabel21.setForeground(Color.black);
        MNameLabel1.setForeground(Color.black);
        SuffixLabel1.setForeground(Color.black);
        SexLabel1.setForeground(Color.black);
        BDateLabel.setForeground(Color.black);
        emailLabel.setForeground(Color.black);
        phoneNumberLabel.setForeground(Color.black);
        blockNum.setForeground(Color.black);
        lotNum.setForeground(Color.black);
        phaseNum.setForeground(Color.black);

    }//GEN-LAST:event_cancelButtonconfirmLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel BDateLabel;
    private javax.swing.JTextField BdateField;
    private javax.swing.JLabel EmailLabel2;
    private javax.swing.JTextField FNameField2;
    private javax.swing.JLabel FNameLabel21;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JTextField LNameField2;
    private javax.swing.JLabel LNameLabel1;
    private javax.swing.JTextField MNameField2;
    private javax.swing.JLabel MNameLabel1;
    private javax.swing.JComboBox<String> SexCombo2;
    private javax.swing.JLabel SexLabel1;
    private javax.swing.JTextField SuffixField2;
    private javax.swing.JLabel SuffixLabel1;
    private javax.swing.JPanel addPeoplePanel;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JLabel bdateLabel2;
    private javax.swing.JLabel blockNum;
    private javax.swing.JTextField blockNumField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirm2Button;
    private javax.swing.JPanel confirmationPanel2;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fnameLabel2;
    private javax.swing.JLabel lotNum;
    private javax.swing.JTextField lotNumField;
    private javax.swing.JLabel phaseNum;
    private javax.swing.JTextField phaseNumField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel pnumberLabel2;
    private javax.swing.JLabel resAddressLabel;
    private javax.swing.JLabel resBdateLabel;
    private javax.swing.JLabel resEmailLabel;
    private javax.swing.JLabel resIDLabel;
    private javax.swing.JLabel resNameLabel;
    private javax.swing.JLabel resPhoneNumberLabel;
    private javax.swing.JLabel resSexLabel1;
    private javax.swing.JPanel residentConfirmPanel;
    private javax.swing.JLabel residentIDLabel;
    private javax.swing.JLabel residentLabel2;
    private javax.swing.JLabel sexLabel2;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
