package Super_Admin;

import Objects.*;
import Objects.Security;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

public class addSec extends javax.swing.JPanel {

    String lname, fname, mname, suf, phone, pass;
    boolean lnameChecker, fnameChecker, mnameChecker, sufChecker, phoneChecker, successChecker;

    /**
     * Creates new form addSec
     */
    public addSec() {
        initComponents();
        confirmationPanel2.setVisible(false);

    }

    public int getNextID() {
        String SqlQuery = "select MAX(StaffID) from SECURITY_PERSONNEL";
        int out = 0;
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
            PreparedStatement pst = conn.prepareStatement(SqlQuery);
            ResultSet rs = pst.executeQuery();
            System.out.println("c");
            if (rs.next()) {
                System.out.println("a");
                out = rs.getInt(1);
                System.out.println(out);
                out++;
            }
        } catch (ClassNotFoundException | SQLException e) {
            return -1;
        }
        return out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPeoplePanel = new javax.swing.JPanel();
        FullNameLabel = new javax.swing.JLabel();
        LNameLabel1 = new javax.swing.JLabel();
        FNameLabel1 = new javax.swing.JLabel();
        MNameLabel1 = new javax.swing.JLabel();
        SuffixLabel1 = new javax.swing.JLabel();
        LNameField2 = new javax.swing.JTextField();
        FNameField2 = new javax.swing.JTextField();
        MNameField2 = new javax.swing.JTextField();
        SuffixField2 = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        confirmationPanel2 = new javax.swing.JPanel();
        residentLabel2 = new javax.swing.JLabel();
        fnameLabel2 = new javax.swing.JLabel();
        pnumberLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        resNameLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        resPhoneNumberLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        resPasswordLabel = new javax.swing.JLabel();
        staffIDLabel = new javax.swing.JLabel();
        secStaffIDLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        addPeoplePanel.setVisible(true);
        addPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));
        addPeoplePanel.setPreferredSize(new java.awt.Dimension(753, 700));

        FullNameLabel.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        FullNameLabel.setText("Full Name");

        LNameLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        LNameLabel1.setText("Last Name*");

        FNameLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        FNameLabel1.setText("First Name*");

        MNameLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        MNameLabel1.setText("Middle Name");

        SuffixLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SuffixLabel1.setText("Suffix");

        LNameField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        LNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameField2ActionPerformed(evt);
            }
        });

        FNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameField2ActionPerformed(evt);
            }
        });

        MNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNameField2ActionPerformed(evt);
            }
        });

        SuffixField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuffixField2ActionPerformed(evt);
            }
        });

        phoneNumberLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        phoneNumberLabel.setText("Phone Number*");

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(46, 110, 76));
        submitButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        passwordLabel.setText("VMS Password*");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPeoplePanelLayout = new javax.swing.GroupLayout(addPeoplePanel);
        addPeoplePanel.setLayout(addPeoplePanelLayout);
        addPeoplePanelLayout.setHorizontalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberLabel)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameLabel1)
                    .addComponent(FullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNameLabel1))
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SuffixField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SuffixLabel1)
                                    .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(submitButton)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(passwordLabel))
                        .addGap(66, 66, 66))
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MNameLabel1)
                            .addComponent(MNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addPeoplePanelLayout.setVerticalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(FullNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addComponent(FNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addComponent(MNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SuffixLabel1)
                                    .addComponent(LNameLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SuffixField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPeoplePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(LNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPeoplePanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(36, 36, 36)))
                .addGap(30, 30, 30)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        residentLabel2.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        residentLabel2.setText("SECURITY INFORMATION");

        fnameLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        fnameLabel2.setText("NAME:");

        pnumberLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        pnumberLabel2.setText("PHONE NUMBER:");

        confirmButton.setBackground(new java.awt.Color(46, 110, 76));
        confirmButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonconfirmLabelActionPerformed(evt);
            }
        });

        resNameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        cancelButton.setBackground(new java.awt.Color(46, 110, 76));
        cancelButton.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonconfirmLabelActionPerformed(evt);
            }
        });

        resPhoneNumberLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N

        passwordLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        passwordLabel1.setText("PASSWORD:");

        resPasswordLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        staffIDLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        staffIDLabel.setForeground(new java.awt.Color(102, 102, 102));
        staffIDLabel.setText("STAFF ID: ");

        secStaffIDLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        secStaffIDLabel.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout confirmationPanel2Layout = new javax.swing.GroupLayout(confirmationPanel2);
        confirmationPanel2.setLayout(confirmationPanel2Layout);
        confirmationPanel2Layout.setHorizontalGroup(
            confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                        .addComponent(fnameLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resNameLabel))
                                    .addComponent(pnumberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(residentLabel2)
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                                .addComponent(staffIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secStaffIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(confirmationPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(confirmButton)
                        .addGap(38, 38, 38)
                        .addComponent(cancelButton)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        confirmationPanel2Layout.setVerticalGroup(
            confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmationPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(residentLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffIDLabel)
                    .addComponent(secStaffIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel2)
                    .addComponent(resNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnumberLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel1)
                    .addComponent(resPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(confirmationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPeoplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(confirmationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPeoplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameField2ActionPerformed

    private void FNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameField2ActionPerformed

    private void MNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNameField2ActionPerformed

    private void SuffixField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuffixField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuffixField2ActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Resident res = new Resident();

        //kukunin laman ng jfield
        lname = LNameField2.getText();
        fname = FNameField2.getText();
        mname = MNameField2.getText();
        suf = SuffixField2.getText();
        phone = phoneNumberField.getText();
        pass = passwordField.getText();

        //gawing black ang text para pag nagreset
        LNameLabel1.setForeground(Color.black);
        FNameLabel1.setForeground(Color.black);
        MNameLabel1.setForeground(Color.black);
        SuffixLabel1.setForeground(Color.black);
        phoneNumberLabel.setForeground(Color.black);

        //check if may laman
        if (!"".equals(lname) && !"".equals(fname) && !"".equals(phone) && !"".equals(pass)) {

            ///check kung tama ang laman
            if (res.isAlpha(lname)) {
                lnameChecker = true;
            } else {
                LNameLabel1.setForeground(Color.red);
            }

            if (res.isAlpha(fname)) {
                fnameChecker = true;
            } else {
                FNameLabel1.setForeground(Color.red);
            }

            if (!MNameField2.getText().isEmpty()) {
                if (res.isAlpha(mname)) {
                    mnameChecker = true;
                } else {
                    MNameLabel1.setForeground(Color.red);
                }
            }

            if (!SuffixField2.getText().isEmpty()) {
                if (res.isAlpha(suf)) {
                    sufChecker = true;
                } else {
                    SuffixLabel1.setForeground(Color.red);
                }
            }

            if (!res.isAlpha(phone) && phone.length() == 11) {
                phoneChecker = true;
            } else {
                phoneNumberLabel.setForeground(Color.red);
            }

            //staff id
            int id = getNextID();

            //set na ng mga info sa confirmation panel
            if (lnameChecker == true && fnameChecker == true && mnameChecker == true && sufChecker == true
                    && phoneChecker == true) {
                confirmationPanel2.setVisible(true);
                secStaffIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + mname + " " + lname + " " + suf);
                resPhoneNumberLabel.setText(phone);
                resPasswordLabel.setText(pass);
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == false && sufChecker == true
                    && phoneChecker == true) {
                confirmationPanel2.setVisible(true);
                secStaffIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + lname + " " + suf);
                resPhoneNumberLabel.setText(phone);
                resPasswordLabel.setText(pass);
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == true && sufChecker == false
                    && phoneChecker == true) {
                confirmationPanel2.setVisible(true);
                secStaffIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + mname + " " + lname);
                resPhoneNumberLabel.setText(phone);
                resPasswordLabel.setText(pass);
            } else if (lnameChecker == true && fnameChecker == true && mnameChecker == false && sufChecker == false
                    && phoneChecker == true) {
                confirmationPanel2.setVisible(true);
                secStaffIDLabel.setText(String.valueOf(id));
                resNameLabel.setText(fname + " " + lname);
                resPhoneNumberLabel.setText(phone);
                resPasswordLabel.setText(pass);
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Input", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kindly Fill Out Required Details", "Message", JOptionPane.INFORMATION_MESSAGE);
        }

        //reset to false
        lnameChecker = false;
        fnameChecker = false;
        mnameChecker = false;
        sufChecker = false;
        phoneChecker = false;
    }//GEN-LAST:event_submitButtonActionPerformed

    private void confirmButtonconfirmLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonconfirmLabelActionPerformed
        Resident res = new Resident();
        Security sec = new Security();

        int checkPhone = 0;
        int checkPhoneRes = 0;
        //checker    
        checkPhone = sec.checkPhone(phone);
        checkPhoneRes = res.checkPhone(phone);

        //If walang record
        if (checkPhone == 0 && checkPhoneRes == 0) {

            int id = getNextID();

            String sql = "insert into security_personnel values(?,?,?,?,?,?,ENCRYPTBYPASSPHRASE('StaffPassword',?),'src/profilePictures/profile.png')";

            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\NETBEANSCONNECT:1433;databaseName=VisitorMS;encrypt=true;trustServerCertificate=true", "sa", "BSIT2AG1");
                System.out.println("Connect to database successful!!");
                successChecker = true;

                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, String.valueOf(id));
                pst.setString(2, lname);
                pst.setString(3, fname);
                if (MNameField2.getText().isEmpty()) {
                    pst.setString(4, null);
                } else {
                    pst.setString(4, mname);
                }

                if (SuffixField2.getText().isEmpty()) {
                    pst.setString(5, null);
                } else {
                    pst.setString(5, suf);
                }

                pst.setString(6, phone);
                pst.setString(7, pass);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Inserted Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                //rs.close();
                conn.close();

            } catch (ClassNotFoundException | SQLException e) {
e.printStackTrace();
            }
        } else {//kapag may record na nito
            JOptionPane.showMessageDialog(null, "This record already exist", "Message", JOptionPane.INFORMATION_MESSAGE);
            if (checkPhone == 1 || checkPhoneRes == 1) {
                phoneNumberLabel.setForeground(Color.red);
            }

        }
        if (successChecker) {
            FNameField2.setText("");
            LNameField2.setText("");
            MNameField2.setText("");
            SuffixField2.setText("");
            phoneNumberField.setText("");
            passwordField.setText("");
            confirmationPanel2.setVisible(false);
            //reset
            successChecker = false;
        }
    }//GEN-LAST:event_confirmButtonconfirmLabelActionPerformed

    private void cancelButtonconfirmLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonconfirmLabelActionPerformed
        FNameField2.setText("");
        LNameField2.setText("");
        MNameField2.setText("");
        SuffixField2.setText("");
        phoneNumberField.setText("");
        passwordField.setText("");
        confirmationPanel2.setVisible(false);
        resNameLabel.setText("");
        resPhoneNumberLabel.setText("");
        resPasswordLabel.setText("");

        //gawing black ang text para pag nagcancel
        LNameLabel1.setForeground(Color.black);
        FNameLabel1.setForeground(Color.black);
        MNameLabel1.setForeground(Color.black);
        SuffixLabel1.setForeground(Color.black);
        phoneNumberLabel.setForeground(Color.black);
    }//GEN-LAST:event_cancelButtonconfirmLabelActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FNameField2;
    private javax.swing.JLabel FNameLabel1;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JTextField LNameField2;
    private javax.swing.JLabel LNameLabel1;
    private javax.swing.JTextField MNameField2;
    private javax.swing.JLabel MNameLabel1;
    private javax.swing.JTextField SuffixField2;
    private javax.swing.JLabel SuffixLabel1;
    private javax.swing.JPanel addPeoplePanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel confirmationPanel2;
    private javax.swing.JLabel fnameLabel2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel pnumberLabel2;
    private javax.swing.JLabel resNameLabel;
    private javax.swing.JLabel resPasswordLabel;
    private javax.swing.JLabel resPhoneNumberLabel;
    private javax.swing.JLabel residentLabel2;
    private javax.swing.JLabel secStaffIDLabel;
    private javax.swing.JLabel staffIDLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
