/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Super_Admin;



/**
 *
 * @author Win10
 */
public class editPeople extends javax.swing.JPanel {

    /**
     * Creates new form editPeople
     */
    public editPeople() {
        initComponents();
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blacklist = new javax.swing.JLabel();
        addBL = new javax.swing.JLabel();
        editResOrSec = new javax.swing.JTabbedPane();
        res = new javax.swing.JPanel();
        editRes1 = new Super_Admin.editRes();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blacklist.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        blacklist.setForeground(new java.awt.Color(30, 30, 30));
        blacklist.setText("Resident");
        add(blacklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 53, -1, -1));

        addBL.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        addBL.setForeground(new java.awt.Color(133, 133, 133));
        addBL.setText("Edit or delete resident in the subdivision");
        add(addBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 121, -1, -1));

        editResOrSec.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        res.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resLayout = new javax.swing.GroupLayout(res);
        res.setLayout(resLayout);
        resLayout.setHorizontalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        resLayout.setVerticalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resLayout.createSequentialGroup()
                .addComponent(editRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        editResOrSec.addTab("tab2", res);

        add(editResOrSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 160, 1290, 560));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBL;
    private javax.swing.JLabel blacklist;
    private Super_Admin.editRes editRes1;
    private javax.swing.JTabbedPane editResOrSec;
    private javax.swing.JPanel res;
    // End of variables declaration//GEN-END:variables
}
