
package Super_Admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import pack1.Home;
import raven.scroll.win11.ScrollBarWin11UI;


public class SuperAdmin extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame
     */
    public SuperAdmin() {
        UIDefaults ui = UIManager.getDefaults();
        ui.put("ScrollBarUI", ScrollBarWin11UI.class.getCanonicalName());
        //Changes Default JFrame ScrollBar to CustomScrollBar by Raven
        // Credits from Original Video https://www.youtube.com/watch?v=keWhddPf_vg
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width;
        int height;
        
        
        System.out.println("Width: " + screenSize.getWidth());
        System.out.println("Height: " + screenSize.getHeight());
        System.out.println("Quotient: " + screenSize.getWidth()/screenSize.getHeight());
        
        if((screenSize.getWidth()/screenSize.getHeight()) == 1.5)/*result ng laptop ko (3:2 aspect ratio)*/{
            width = (int)(screenSize.getWidth()*0.9);
            height = (int)(screenSize.getHeight()*0.9);
        } else /*if((screenSize.getWidth()/screenSize.getHeight()) == 1.7777777777777777) eto kasi result nung sa monitor q (16:9 ratio)*/{
            width = (int)(screenSize.getWidth()*0.675);
            height = (int)(screenSize.getHeight()*0.9);
        }
        setSize(width,height);

        setLocationRelativeTo(null);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        mainLogo = new javax.swing.JLabel();
        systemNameLabel = new javax.swing.JLabel();
        mainLogo1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        toolbarPanel = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        addPeopleButton = new javax.swing.JLabel();
        separator1 = new javax.swing.JLabel();
        editPeopleButton = new javax.swing.JLabel();
        MainMenuTabbedPane1 = new javax.swing.JTabbedPane();
        addPeoplePanel = new javax.swing.JPanel();
        addPeopleSA1 = new Super_Admin.addPeopleSA();
        editPeoplePanel = new javax.swing.JPanel();
        editPeople1 = new Super_Admin.editPeople();
        delPeoplePanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        groupmemberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Benilde Subdivision Visitor Management System [Super Admin]");
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(46, 110, 76));
        headerPanel.setPreferredSize(new java.awt.Dimension(1280, 93));

        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        mainLogo.setText("jLabel1");
        mainLogo.setMaximumSize(new java.awt.Dimension(100, 100));
        mainLogo.setMinimumSize(new java.awt.Dimension(100, 100));
        mainLogo.setPreferredSize(new java.awt.Dimension(100, 100));

        systemNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        systemNameLabel.setFont(new java.awt.Font("Calibri", 1, 64)); // NOI18N
        systemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        systemNameLabel.setText("BENILDE SUBDIVISION");
        systemNameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        systemNameLabel.setMaximumSize(new java.awt.Dimension(700, 61));
        systemNameLabel.setMinimumSize(new java.awt.Dimension(700, 61));
        systemNameLabel.setPreferredSize(new java.awt.Dimension(700, 61));

        mainLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        mainLogo1.setText("jLabel1");
        mainLogo1.setMaximumSize(new java.awt.Dimension(100, 100));
        mainLogo1.setMinimumSize(new java.awt.Dimension(100, 100));
        mainLogo1.setPreferredSize(new java.awt.Dimension(100, 100));

        logoutButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(46, 110, 76));
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(mainLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1174, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(mainLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(systemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addGap(26, 26, 26))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(systemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        toolbarPanel.setBackground(new java.awt.Color(30, 30, 30));
        toolbarPanel.setFloatable(false);
        toolbarPanel.setAlignmentX(0.0F);
        toolbarPanel.setPreferredSize(new java.awt.Dimension(1280, 70));

        jLabel1.setText("          ");
        toolbarPanel.add(jLabel1);

        addPeopleButton.setBackground(new java.awt.Color(255, 255, 255));
        addPeopleButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        addPeopleButton.setForeground(new java.awt.Color(255, 255, 255));
        addPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/addIcon.png"))); // NOI18N
        addPeopleButton.setText("  ADD PEOPLE   ");
        addPeopleButton.setToolTipText("");
        addPeopleButton.setAlignmentY(0.0F);
        addPeopleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPeopleButton.setMaximumSize(new java.awt.Dimension(250, 72));
        addPeopleButton.setMinimumSize(new java.awt.Dimension(250, 72));
        addPeopleButton.setPreferredSize(new java.awt.Dimension(250, 69));
        addPeopleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPeopleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPeopleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPeopleButtonMouseExited(evt);
            }
        });
        toolbarPanel.add(addPeopleButton);

        separator1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Line.png"))); // NOI18N
        separator1.setText("          ");
        separator1.setAlignmentY(0.0F);
        separator1.setMaximumSize(new java.awt.Dimension(40, 70));
        separator1.setMinimumSize(new java.awt.Dimension(40, 70));
        separator1.setPreferredSize(new java.awt.Dimension(40, 70));
        toolbarPanel.add(separator1);

        editPeopleButton.setBackground(new java.awt.Color(255, 255, 255));
        editPeopleButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        editPeopleButton.setForeground(new java.awt.Color(255, 255, 255));
        editPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit55.png"))); // NOI18N
        editPeopleButton.setText("EDIT RESIDENT");
        editPeopleButton.setToolTipText("");
        editPeopleButton.setAlignmentY(0.0F);
        editPeopleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPeopleButton.setMaximumSize(new java.awt.Dimension(346, 69));
        editPeopleButton.setMinimumSize(new java.awt.Dimension(346, 69));
        editPeopleButton.setName(""); // NOI18N
        editPeopleButton.setPreferredSize(new java.awt.Dimension(346, 69));
        editPeopleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPeopleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPeopleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPeopleButtonMouseExited(evt);
            }
        });
        toolbarPanel.add(editPeopleButton);

        jPanel1.add(toolbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 1290, -1));

        MainMenuTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));
        MainMenuTabbedPane1.setPreferredSize(new java.awt.Dimension(1280, 750));

        addPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout addPeoplePanelLayout = new javax.swing.GroupLayout(addPeoplePanel);
        addPeoplePanel.setLayout(addPeoplePanelLayout);
        addPeoplePanelLayout.setHorizontalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addPeopleSA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addPeoplePanelLayout.setVerticalGroup(
            addPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPeoplePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addPeopleSA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainMenuTabbedPane1.addTab("tab1", addPeoplePanel);

        editPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));
        editPeoplePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        editPeoplePanel.add(editPeople1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainMenuTabbedPane1.addTab("tab2", editPeoplePanel);

        delPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout delPeoplePanelLayout = new javax.swing.GroupLayout(delPeoplePanel);
        delPeoplePanel.setLayout(delPeoplePanelLayout);
        delPeoplePanelLayout.setHorizontalGroup(
            delPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        delPeoplePanelLayout.setVerticalGroup(
            delPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );

        MainMenuTabbedPane1.addTab("tab3", delPeoplePanel);

        jPanel1.add(MainMenuTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1280, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        footerPanel.setBackground(new java.awt.Color(30, 30, 30));
        footerPanel.setAlignmentX(0.0F);
        footerPanel.setAlignmentY(0.0F);
        footerPanel.setPreferredSize(new java.awt.Dimension(1280, 46));

        groupmemberLabel.setBackground(new java.awt.Color(255, 255, 255));
        groupmemberLabel.setFont(new java.awt.Font("Circular Std Book", 0, 10)); // NOI18N
        groupmemberLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupmemberLabel.setText("                                                                         Aguilar, Meneses, Quiroz, Sandoval, Velasco | BSIT 2A-G1");
        groupmemberLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(762, Short.MAX_VALUE)
                .addComponent(groupmemberLabel)
                .addGap(20, 20, 20))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupmemberLabel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPeopleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPeopleButtonMouseClicked
        MainMenuTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_addPeopleButtonMouseClicked

    private void addPeopleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPeopleButtonMouseEntered
        addPeopleButton.setForeground(new java.awt.Color(46, 110, 76));
        addPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/addIconHover.png")));

    }//GEN-LAST:event_addPeopleButtonMouseEntered

    private void addPeopleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPeopleButtonMouseExited
        addPeopleButton.setForeground(new java.awt.Color(255, 255, 255));
        addPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/addIcon.png")));
    }//GEN-LAST:event_addPeopleButtonMouseExited

    private void editPeopleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPeopleButtonMouseEntered
        editPeopleButton.setForeground(new java.awt.Color(46, 110, 76));
        editPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit55.png"))); // NOI18N
    }//GEN-LAST:event_editPeopleButtonMouseEntered

    private void editPeopleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPeopleButtonMouseExited
        editPeopleButton.setForeground(new java.awt.Color(255, 255, 255));
        editPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit55.png"))); // NOI18N
    }//GEN-LAST:event_editPeopleButtonMouseExited

    private void editPeopleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPeopleButtonMouseClicked
        MainMenuTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_editPeopleButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
      Home home = new Home();
      home.setVisible(true);
      setVisible(false);
      dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SuperAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainMenuTabbedPane1;
    private javax.swing.JLabel addPeopleButton;
    private javax.swing.JPanel addPeoplePanel;
    private Super_Admin.addPeopleSA addPeopleSA1;
    private javax.swing.JPanel delPeoplePanel;
    private Super_Admin.editPeople editPeople1;
    private javax.swing.JLabel editPeopleButton;
    private javax.swing.JPanel editPeoplePanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel groupmemberLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel mainLogo1;
    private javax.swing.JLabel separator1;
    private javax.swing.JLabel systemNameLabel;
    private javax.swing.JToolBar toolbarPanel;
    // End of variables declaration//GEN-END:variables
}
